# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.1.227:3306/slinceob?Unicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 
  session:
    store-type: none
    
# 服务端口配置
server:
  port: 80
 
#安全相关配置
#security:
#  basic:
#    enabled: false

# 自定义安全框架配置项
slince:
  security:
#之下为验证码相关配置
    code:
      image:
        width: 120                      # 图形验证码宽度     默认是：120
        height: 40                      # 高度                           默认是：40
        line-count: 20                  # 干扰线条数             默认是：20
        length: 4                       # 字符长度                  默认是：4
        expireIn: 60                    # 过期时间                  默认是：60
          

# 之下为登录跳转的配置
    browser:
#      loginPage: /demo-login.html      # 登录页面，没有配置时，跳转到标准登录界面/slince-login.html
      signUpUrl: /demo-signUp.html
#      logout-url: /demo-login.html     # 退出成功后，跳转的页面，        默认配置为：json，返回json格式的数据
      loginType: REDIRECT               # 配置登录成功或失败后的处理方式：REDIRECT,JSON
    
# 之下为spring-social相关配置（第三方登录）
    social:
      filterProcessesUrl: /login
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        
      weixin:
        app-id: wxfd6965ab1fc6adb2
        app-secret: 66bb4566de776ac699ec1dbed0cc3dd1
        
         
 
    
